### ISSUE TITLE
filter model missing $notin

### ISSUE THREAD

**Issue by mxdi9i7** [datocms/website#15]
I think its useful for ID model filters to have an $notin filter type, so I can exclude results based on an array of IDs

**Comment by matjack1** [comment]
thank you @mxdi9i7 for your suggestion!

I think it makes complete sense to add, but can you please add a feature request over here: https://github.com/datocms/product-roadmap/issues/new?assignees=&labels=&template=feature_request.md&title=

This repository is only meant for our public website.

Thanks!
