### ISSUE TITLE
Pricing page is showing the columns twice

### ISSUE THREAD

**Issue by marcinsydor** [datocms/website#27]
As you can see the pricing page is not showing well the content.

![image](https://user-images.githubusercontent.com/13141089/66324894-3c366800-e91e-11e9-81a4-862f30ae9d2c.png)

Tested on latest Chrome and Firefox on macOS

**Comment by stefanoverna** [comment]
ahaha, so sorry, that's clearly a bug. it's already being fixed :D
thanks for reporting it!
