### ISSUE TITLE
Vulnerability detection on your site

### ISSUE THREAD

**Issue by Mearafat** [datocms/website#35]
Hi,

This is Yeasir Arafat here. I have found some security vulnerability on your site. Do you have any bug bounty program or any other way that I can send you the bug report? 

-Thanks!

**Comment by matjack1** [comment]
Hey @Mearafat please send the details over at support@datocms.com

We offer bug bounties for confirmed security vulnerabilities. Depending on the severity of the bug we offer different rewards, we don't have standard quotes as now, sorry.

I'm closing this for now, please continue over email for any additional detail.

Thank you!
